services:
  dev:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/yingchaoorg/local_docs-amis-doc:master
    privileged: false
    container_name: local-docs-amis-main-docs
    volumes:
      - .:/home/node/www
    tty: true
    ports:
      - 34814:80
